var GEPCP = {
	books: [
		{
			name: "Galatians",
			abbreviation: "G",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle - sent not from men nor by a man, but by Jesus Christ and God the Father, who raised him from the dead - ",
								"and all the brothers and sisters[a] with me, To the churches in Galatia:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ,",
								"who gave himself for our sins to rescue us from the present evil age, according to the will of our God and Father,",
								"to whom be glory for ever and ever. Amen.",
							],
						},
						{
							title: "No Other Gospel",
							verses: [
								"I am astonished that you are so quickly deserting the one who called you to live in the grace of Christ and are turning to a different gospel - ",
								"which is really no gospel at all. Evidently some people are throwing you into confusion and are trying to pervert the gospel of Christ.",
								"But even if we or an angel from heaven should preach a gospel other than the one we preached to you, let them be under God's curse!",
								"As we have already said, so now I say again: If anybody is preaching to you a gospel other than what you accepted, let them be under God's curse!",
								"Am I now trying to win the approval of human beings, or of God? Or am I trying to please people? If I were still trying to please people, I would not be a servant of Christ.",
							],
						},
						{
							title: "Paul Called by God",
							verses: [
								"I want you to know, brothers and sisters, that the gospel I preached is not of human origin.",
								"I did not receive it from any man, nor was I taught it; rather, I received it by revelation from Jesus Christ.",
								"For you have heard of my previous way of life in Judaism, how intensely I persecuted the church of God and tried to destroy it.",
								"I was advancing in Judaism beyond many of my own age among my people and was extremely zealous for the traditions of my fathers.",
								"But when God, who set me apart from my mother's womb and called me by his grace, was pleased",
								"to reveal his Son in me so that I might preach him among the Gentiles, my immediate response was not to consult any human being.",
								"I did not go up to Jerusalem to see those who were apostles before I was, but I went into Arabia. Later I returned to Damascus.",
								"Then after three years, I went up to Jerusalem to get acquainted with Cephas[b] and stayed with him fifteen days.",
								"I saw none of the other apostles - only James, the Lord's brother.",
								"I assure you before God that what I am writing you is no lie.",
								"Then I went to Syria and Cilicia.",
								"I was personally unknown to the churches of Judea that are in Christ.",
								'They only heard the report: "The man who formerly persecuted us is now preaching the faith he once tried to destroy."',
								"And they praised God because of me.",
							],
						},
					],
					footnotes: {
						a: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in verse 11; and in 3:15; 4:12, 28, 31; 5:11, 13; 6:1, 18.",
						b: "That is, Peter",
					},
				},
				{
					sections: [
						{
							title: "Paul Accepted by the Apostles",
							verses: [
								"Then after fourteen years, I went up again to Jerusalem, this time with Barnabas. I took Titus along also.",
								"I went in response to a revelation and, meeting privately with those esteemed as leaders, I presented to them the gospel that I preach among the Gentiles. I wanted to be sure I was not running and had not been running my race in vain.",
								"Yet not even Titus, who was with me, was compelled to be circumcised, even though he was a Greek.",
								"This matter arose because some false believers had infiltrated our ranks to spy on the freedom we have in Christ Jesus and to make us slaves.",
								"We did not give in to them for a moment, so that the truth of the gospel might be preserved for you.",
								"As for those who were held in high esteem - whatever they were makes no difference to me; God does not show favoritism - they added nothing to my message.",
								"On the contrary, they recognized that I had been entrusted with the task of preaching the gospel to the uncircumcised,[a] just as Peter had been to the circumcised.[b]",
								"For God, who was at work in Peter as an apostle to the circumcised, was also at work in me as an apostle to the Gentiles.",
								"James, Cephas[c] and John, those esteemed as pillars, gave me and Barnabas the right hand of fellowship when they recognized the grace given to me. They agreed that we should go to the Gentiles, and they to the circumcised.",
								"All they asked was that we should continue to remember the poor, the very thing I had been eager to do all along.",
							],
						},
						{
							title: "Paul Opposes Cephas",
							verses: [
								"When Cephas came to Antioch, I opposed him to his face, because he stood condemned.",
								"For before certain men came from James, he used to eat with the Gentiles. But when they arrived, he began to draw back and separate himself from the Gentiles because he was afraid of those who belonged to the circumcision group.",
								"The other Jews joined him in his hypocrisy, so that by their hypocrisy even Barnabas was led astray.",
								'When I saw that they were not acting in line with the truth of the gospel, I said to Cephas in front of them all, "You are a Jew, yet you live like a Gentile and not like a Jew. How is it, then, that you force Gentiles to follow Jewish customs?',
								'"We who are Jews by birth and not sinful Gentiles',
								"know that a person is not justified by the works of the law, but by faith in Jesus Christ. So we, too, have put our faith in Christ Jesus that we may be justified by faith in[d] Christ and not by the works of the law, because by the works of the law no one will be justified.",
								"\"But if, in seeking to be justified in Christ, we Jews find ourselves also among the sinners, doesn't that mean that Christ promotes sin? Absolutely not!",
								"If I rebuild what I destroyed, then I really would be a lawbreaker.",
								'"For through the law I died to the law so that I might live for God.',
								"I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.",
								'I do not set aside the grace of God, for if righteousness could be gained through the law, Christ died for nothing!"[e]',
							],
						},
					],
					footnotes: {
						a: "That is, Gentiles",
						b: "That is, Jews; also in verses 8 and 9",
						c: "That is, Peter; also in verses 11 and 14",
						d: "Or _but through the faithfulness of … justified on the basis of the faithfulness of_",
						e: "Some interpreters end the quotation after verse 14.",
					},
				},
				{
					sections: [
						{
							title: "Faith or Works of the Law",
							verses: [
								"You foolish Galatians! Who has bewitched you? Before your very eyes Jesus Christ was clearly portrayed as crucified.",
								"I would like to learn just one thing from you: Did you receive the Spirit by the works of the law, or by believing what you heard?",
								"Are you so foolish? After beginning by means of the Spirit, are you now trying to finish by means of the flesh?[a]",
								"Have you experienced[b] so much in vain - if it really was in vain?",
								"So again I ask, does God give you his Spirit and work miracles among you by the works of the law, or by your believing what you heard?",
								'So also Abraham "believed God, and it was credited to him as righteousness."[c]',
								"Understand, then, that those who have faith are children of Abraham.",
								'Scripture foresaw that God would justify the Gentiles by faith, and announced the gospel in advance to Abraham: "All nations will be blessed through you."[d]',
								"So those who rely on faith are blessed along with Abraham, the man of faith.",
								'For all who rely on the works of the law are under a curse, as it is written: "Cursed is everyone who does not continue to do everything written in the Book of the Law."[e]',
								'Clearly no one who relies on the law is justified before God, because "the righteous will live by faith."[f]',
								'The law is not based on faith; on the contrary, it says, "The person who does these things will live by them."[g]',
								'Christ redeemed us from the curse of the law by becoming a curse for us, for it is written: "Cursed is everyone who is hung on a pole."[h]',
								"He redeemed us in order that the blessing given to Abraham might come to the Gentiles through Christ Jesus, so that by faith we might receive the promise of the Spirit.",
							],
						},
						{
							title: "The Law and the Promise",
							verses: [
								"Brothers and sisters, let me take an example from everyday life. Just as no one can set aside or add to a human covenant that has been duly established, so it is in this case.",
								'The promises were spoken to Abraham and to his seed. Scripture does not say "and to seeds," meaning many people, but "and to your seed,"[i] meaning one person, who is Christ.',
								"What I mean is this: The law, introduced 430 years later, does not set aside the covenant previously established by God and thus do away with the promise.",
								"For if the inheritance depends on the law, then it no longer depends on the promise; but God in his grace gave it to Abraham through a promise.",
								"Why, then, was the law given at all? It was added because of transgressions until the Seed to whom the promise referred had come. The law was given through angels and entrusted to a mediator.",
								"A mediator, however, implies more than one party; but God is one.",
								"Is the law, therefore, opposed to the promises of God? Absolutely not! For if a law had been given that could impart life, then righteousness would certainly have come by the law.",
								"But Scripture has locked up everything under the control of sin, so that what was promised, being given through faith in Jesus Christ, might be given to those who believe.",
							],
						},
						{
							title: "Children of God",
							verses: [
								"Before the coming of this faith,[j] we were held in custody under the law, locked up until the faith that was to come would be revealed.",
								"So the law was our guardian until Christ came that we might be justified by faith.",
								"Now that this faith has come, we are no longer under a guardian.",
								"So in Christ Jesus you are all children of God through faith,",
								"for all of you who were baptized into Christ have clothed yourselves with Christ.",
								"There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus.",
								"If you belong to Christ, then you are Abraham's seed, and heirs according to the promise.",
							],
						},
					],
					footnotes: {
						a: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit.",
						b: "Or _suffered_",
						c: "Gen. 15:6",
						d: "Gen. 12:3; 18:18; 22:18",
						e: "Deut. 27:26",
						f: "Hab. 2:4",
						g: "Lev. 18:5",
						h: "Deut. 21:23",
						i: "Gen. 12:7; 13:15; 24:7",
						j: "Or _through the faithfulness of Jesus … {23}Before faith came_",
					},
				},
				{
					sections: [
						{
							title: "Children of God (Continued)",
							verses: [
								"What I am saying is that as long as an heir is underage, he is no different from a slave, although he owns the whole estate.",
								"The heir is subject to guardians and trustees until the time set by his father.",
								"So also, when we were underage, we were in slavery under the elemental spiritual forces[a] of the world.",
								"But when the set time had fully come, God sent his Son, born of a woman, born under the law,",
								"to redeem those under the law, that we might receive adoption to sonship.[b]",
								'Because you are his sons, God sent the Spirit of his Son into our hearts, the Spirit who calls out, "Abba,[c] Father."',
								"So you are no longer a slave, but God's child; and since you are his child, God has made you also an heir.",
							],
						},
						{
							title: "Paul's Concern for the Galatians",
							verses: [
								"Formerly, when you did not know God, you were slaves to those who by nature are not gods.",
								"But now that you know God - or rather are known by God - how is it that you are turning back to those weak and miserable forces[d]? Do you wish to be enslaved by them all over again?",
								"You are observing special days and months and seasons and years!",
								"I fear for you, that somehow I have wasted my efforts on you.",
								"I plead with you, brothers and sisters, become like me, for I became like you. You did me no wrong.",
								"As you know, it was because of an illness that I first preached the gospel to you,",
								"and even though my illness was a trial to you, you did not treat me with contempt or scorn. Instead, you welcomed me as if I were an angel of God, as if I were Christ Jesus himself.",
								"Where, then, is your blessing of me now? I can testify that, if you could have done so, you would have torn out your eyes and given them to me.",
								"Have I now become your enemy by telling you the truth?",
								"Those people are zealous to win you over, but for no good. What they want is to alienate you from us, so that you may have zeal for them.",
								"It is fine to be zealous, provided the purpose is good, and to be so always, not just when I am with you.",
								"My dear children, for whom I am again in the pains of childbirth until Christ is formed in you,",
								"how I wish I could be with you now and change my tone, because I am perplexed about you!",
							],
						},
						{
							title: "Hagar and Sarah",
							verses: [
								"Tell me, you who want to be under the law, are you not aware of what the law says?",
								"For it is written that Abraham had two sons, one by the slave woman and the other by the free woman.",
								"His son by the slave woman was born according to the flesh, but his son by the free woman was born as the result of a divine promise.",
								"These things are being taken figuratively: The women represent two covenants. One covenant is from Mount Sinai and bears children who are to be slaves: This is Hagar.",
								"Now Hagar stands for Mount Sinai in Arabia and corresponds to the present city of Jerusalem, because she is in slavery with her children.",
								"But the Jerusalem that is above is free, and she is our mother.",
								'For it is written: "Be glad, barren woman, you who never bore a child; shout for joy and cry aloud, you who were never in labor; because more are the children of the desolate woman than of her who has a husband."[e]',
								"Now you, brothers and sisters, like Isaac, are children of promise.",
								"At that time the son born according to the flesh persecuted the son born by the power of the Spirit. It is the same now.",
								"But what does Scripture say? \"Get rid of the slave woman and her son, for the slave woman's son will never share in the inheritance with the free woman's son.\"[f]",
								"Therefore, brothers and sisters, we are not children of the slave woman, but of the free woman.",
							],
						},
					],
					footnotes: {
						a: "Or _under the basic principles_",
						b: "The Greek word for _adoption to sonship_ is a legal term referring to the full legal standing of an adopted male heir in Roman culture.",
						c: "Aramaic for _Father_",
						d: "Or _principles_",
						e: "Isaiah 54:1",
						f: "Gen. 21:10",
					},
				},
				{
					sections: [
						{
							title: "Freedom in Christ",
							verses: [
								"It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.",
								"Mark my words! I, Paul, tell you that if you let yourselves be circumcised, Christ will be of no value to you at all.",
								"Again I declare to every man who lets himself be circumcised that he is obligated to obey the whole law.",
								"You who are trying to be justified by the law have been alienated from Christ; you have fallen away from grace.",
								"For through the Spirit we eagerly await by faith the righteousness for which we hope.",
								"For in Christ Jesus neither circumcision nor uncircumcision has any value. The only thing that counts is faith expressing itself through love.",
								"You were running a good race. Who cut in on you to keep you from obeying the truth?",
								"That kind of persuasion does not come from the one who calls you.",
								'"A little yeast works through the whole batch of dough."',
								"I am confident in the Lord that you will take no other view. The one who is throwing you into confusion, whoever that may be, will have to pay the penalty.",
								"Brothers and sisters, if I am still preaching circumcision, why am I still being persecuted? In that case the offense of the cross has been abolished.",
								"As for those agitators, I wish they would go the whole way and emasculate themselves!",
							],
						},
						{
							title: "Life by the Spirit",
							verses: [
								"You, my brothers and sisters, were called to be free. But do not use your freedom to indulge the flesh[a]; rather, serve one another humbly in love.",
								'For the entire law is fulfilled in keeping this one command: "Love your neighbor as yourself."[b]',
								"If you bite and devour each other, watch out or you will be destroyed by each other.",
								"So I say, walk by the Spirit, and you will not gratify the desires of the flesh.",
								"For the flesh desires what is contrary to the Spirit, and the Spirit what is contrary to the flesh. They are in conflict with each other, so that you are not to do whatever[c] you want.",
								"But if you are led by the Spirit, you are not under the law.",
								"The acts of the flesh are obvious: sexual immorality, impurity and debauchery;",
								"idolatry and witchcraft; hatred, discord, jealousy, fits of rage, selfish ambition, dissensions, factions",
								"and envy; drunkenness, orgies, and the like. I warn you, as I did before, that those who live like this will not inherit the kingdom of God.",
								"But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness,",
								"gentleness and self-control. Against such things there is no law.",
								"Those who belong to Christ Jesus have crucified the flesh with its passions and desires.",
								"Since we live by the Spirit, let us keep in step with the Spirit.",
								"Let us not become conceited, provoking and envying each other.",
							],
						},
					],
					footnotes: {
						a: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit; also in verses 16, 17, 19 and 24; and in 6:8.",
						b: "Lev. 19:18",
						c: "Or _you do not do what_",
					},
				},
				{
					sections: [
						{
							title: "Doing Good to All",
							verses: [
								"Brothers and sisters, if someone is caught in a sin, you who live by the Spirit should restore that person gently. But watch yourselves, or you also may be tempted.",
								"Carry each other's burdens, and in this way you will fulfill the law of Christ.",
								"If anyone thinks they are something when they are not, they deceive themselves.",
								"Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else,",
								"for each one should carry their own load.",
								"Nevertheless, the one who receives instruction in the word should share all good things with their instructor.",
								"Do not be deceived: God cannot be mocked. A man reaps what he sows.",
								"Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.",
								"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
								"Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.",
							],
						},
						{
							title: "Not Circumcision but the New Creation",
							verses: [
								"See what large letters I use as I write to you with my own hand!",
								"Those who want to impress people by means of the flesh are trying to compel you to be circumcised. The only reason they do this is to avoid being persecuted for the cross of Christ.",
								"Not even those who are circumcised keep the law, yet they want you to be circumcised that they may boast about your circumcision in the flesh.",
								"May I never boast except in the cross of our Lord Jesus Christ, through which[a] the world has been crucified to me, and I to the world.",
								"Neither circumcision nor uncircumcision means anything; what counts is the new creation.",
								"Peace and mercy to all who follow this rule - to[b] the Israel of God.",
								"From now on, let no one cause me trouble, for I bear on my body the marks of Jesus.",
								"The grace of our Lord Jesus Christ be with your spirit, brothers and sisters. Amen.",
							],
						},
					],
					footnotes: {
						a: "Or _whom_",
						b: "Or _rule and to_",
					},
				},
			],
		},
		{
			name: "Ephesians",
			abbreviation: "E",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle of Christ Jesus by the will of God, To God's holy people in Ephesus,[a] the faithful in Christ Jesus:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Praise for Spiritual Blessings in Christ",
							verses: [
								"Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.",
								"For he chose us in him before the creation of the world to be holy and blameless in his sight. In love",
								"he[b] predestined us for adoption to sonship[c] through Jesus Christ, in accordance with his pleasure and will - ",
								"to the praise of his glorious grace, which he has freely given us in the One he loves.",
								"In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace",
								"that he lavished on us. With all wisdom and understanding,",
								"he[d] made known to us the mystery of his will according to his good pleasure, which he purposed in Christ,",
								"to be put into effect when the times reach their fulfillment - to bring unity to all things in heaven and on earth under Christ.",
								"In him we were also chosen,[e] having been predestined according to the plan of him who works out everything in conformity with the purpose of his will,",
								"in order that we, who were the first to put our hope in Christ, might be for the praise of his glory.",
								"And you also were included in Christ when you heard the message of truth, the gospel of your salvation. When you believed, you were marked in him with a seal, the promised Holy Spirit,",
								"who is a deposit guaranteeing our inheritance until the redemption of those who are God's possession - to the praise of his glory.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"For this reason, ever since I heard about your faith in the Lord Jesus and your love for all God's people,",
								"I have not stopped giving thanks for you, remembering you in my prayers.",
								"I keep asking that the God of our Lord Jesus Christ, the glorious Father, may give you the Spirit[f] of wisdom and revelation, so that you may know him better.",
								"I pray that the eyes of your heart may be enlightened in order that you may know the hope to which he has called you, the riches of his glorious inheritance in his holy people,",
								"and his incomparably great power for us who believe. That power is the same as the mighty strength",
								"he exerted when he raised Christ from the dead and seated him at his right hand in the heavenly realms,",
								"far above all rule and authority, power and dominion, and every name that is invoked, not only in the present age but also in the one to come.",
								"And God placed all things under his feet and appointed him to be head over everything for the church,",
								"which is his body, the fullness of him who fills everything in every way.",
							],
						},
					],
					footnotes: {
						a: "Some early manuscripts do not have _in Ephesus._",
						b: "Or _sight in love. {5} He_",
						c: "The Greek word for _adoption to sonship_ is a legal term referring to the full legal standing of an adopted male heir in Roman culture.",
						d: "Or _us with all wisdom and understanding. {9} And he_",
						e: "Or _were made heirs_",
						f: "Or _a spirit_",
					},
				},
				{
					sections: [
						{
							title: "Made Alive in Christ",
							verses: [
								"As for you, you were dead in your transgressions and sins,",
								"in which you used to live when you followed the ways of this world and of the ruler of the kingdom of the air, the spirit who is now at work in those who are disobedient.",
								"All of us also lived among them at one time, gratifying the cravings of our flesh[a] and following its desires and thoughts. Like the rest, we were by nature deserving of wrath.",
								"But because of his great love for us, God, who is rich in mercy,",
								"made us alive with Christ even when we were dead in transgressions - it is by grace you have been saved.",
								"And God raised us up with Christ and seated us with him in the heavenly realms in Christ Jesus,",
								"in order that in the coming ages he might show the incomparable riches of his grace, expressed in his kindness to us in Christ Jesus.",
								"For it is by grace you have been saved, through faith - and this is not from yourselves, it is the gift of God - ",
								"not by works, so that no one can boast.",
								"For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.",
							],
						},
						{
							title: "Jew and Gentile Reconciled Through Christ",
							verses: [
								'Therefore, remember that formerly you who are Gentiles by birth and called "uncircumcised" by those who call themselves "the circumcision" (which is done in the body by human hands) - ',
								"remember that at that time you were separate from Christ, excluded from citizenship in Israel and foreigners to the covenants of the promise, without hope and without God in the world.",
								"But now in Christ Jesus you who once were far away have been brought near by the blood of Christ.",
								"For he himself is our peace, who has made the two groups one and has destroyed the barrier, the dividing wall of hostility,",
								"by setting aside in his flesh the law with its commands and regulations. His purpose was to create in himself one new humanity out of the two, thus making peace,",
								"and in one body to reconcile both of them to God through the cross, by which he put to death their hostility.",
								"He came and preached peace to you who were far away and peace to those who were near.",
								"For through him we both have access to the Father by one Spirit.",
								"Consequently, you are no longer foreigners and strangers, but fellow citizens with God's people and also members of his household,",
								"built on the foundation of the apostles and prophets, with Christ Jesus himself as the chief cornerstone.",
								"In him the whole building is joined together and rises to become a holy temple in the Lord.",
								"And in him you too are being built together to become a dwelling in which God lives by his Spirit.",
							],
						},
					],
					footnotes: {
						a: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit.",
					},
				},
				{
					sections: [
						{
							title: "God's Marvelous Plan for the Gentiles",
							verses: [
								"For this reason I, Paul, the prisoner of Christ Jesus for the sake of you Gentiles - ",
								"Surely you have heard about the administration of God's grace that was given to me for you,",
								"that is, the mystery made known to me by revelation, as I have already written briefly.",
								"In reading this, then, you will be able to understand my insight into the mystery of Christ,",
								"which was not made known to people in other generations as it has now been revealed by the Spirit to God's holy apostles and prophets.",
								"This mystery is that through the gospel the Gentiles are heirs together with Israel, members together of one body, and sharers together in the promise in Christ Jesus.",
								"I became a servant of this gospel by the gift of God's grace given me through the working of his power.",
								"Although I am less than the least of all the Lord's people, this grace was given me: to preach to the Gentiles the boundless riches of Christ,",
								"and to make plain to everyone the administration of this mystery, which for ages past was kept hidden in God, who created all things.",
								"His intent was that now, through the church, the manifold wisdom of God should be made known to the rulers and authorities in the heavenly realms,",
								"according to his eternal purpose that he accomplished in Christ Jesus our Lord.",
								"In him and through faith in him we may approach God with freedom and confidence.",
								"I ask you, therefore, not to be discouraged because of my sufferings for you, which are your glory.",
							],
						},
						{
							title: "A Prayer for the Ephesians",
							verses: [
								"For this reason I kneel before the Father,",
								"from whom every family[a] in heaven and on earth derives its name.",
								"I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being,",
								"so that Christ may dwell in your hearts through faith. And I pray that you, being rooted and established in love,",
								"may have power, together with all the Lord's holy people, to grasp how wide and long and high and deep is the love of Christ,",
								"and to know this love that surpasses knowledge - that you may be filled to the measure of all the fullness of God.",
								"Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us,",
								"to him be glory in the church and in Christ Jesus throughout all generations, for ever and ever! Amen.",
							],
						},
					],
					footnotes: {
						a: "The Greek for _family_ (_patria_) is derived from the Greek for _father_ (_pater_).",
					},
				},
				{
					sections: [
						{
							title: "Unity and Maturity in the Body of Christ",
							verses: [
								"As a prisoner for the Lord, then, I urge you to live a life worthy of the calling you have received.",
								"Be completely humble and gentle; be patient, bearing with one another in love.",
								"Make every effort to keep the unity of the Spirit through the bond of peace.",
								"There is one body and one Spirit, just as you were called to one hope when you were called;",
								"one Lord, one faith, one baptism;",
								"one God and Father of all, who is over all and through all and in all.",
								"But to each one of us grace has been given as Christ apportioned it.",
								'This is why it[a] says: "When he ascended on high, he took many captives and gave gifts to his people."[b]',
								'(What does "he ascended" mean except that he also descended to the lower, earthly regions[c]?',
								"He who descended is the very one who ascended higher than all the heavens, in order to fill the whole universe.)",
								"So Christ himself gave the apostles, the prophets, the evangelists, the pastors and teachers,",
								"to equip his people for works of service, so that the body of Christ may be built up",
								"until we all reach unity in the faith and in the knowledge of the Son of God and become mature, attaining to the whole measure of the fullness of Christ.",
								"Then we will no longer be infants, tossed back and forth by the waves, and blown here and there by every wind of teaching and by the cunning and craftiness of people in their deceitful scheming.",
								"Instead, speaking the truth in love, we will grow to become in every respect the mature body of him who is the head, that is, Christ.",
								"From him the whole body, joined and held together by every supporting ligament, grows and builds itself up in love, as each part does its work.",
							],
						},
						{
							title: "Instructions for Christian Living",
							verses: [
								"So I tell you this, and insist on it in the Lord, that you must no longer live as the Gentiles do, in the futility of their thinking.",
								"They are darkened in their understanding and separated from the life of God because of the ignorance that is in them due to the hardening of their hearts.",
								"Having lost all sensitivity, they have given themselves over to sensuality so as to indulge in every kind of impurity, and they are full of greed.",
								"That, however, is not the way of life you learned",
								"when you heard about Christ and were taught in him in accordance with the truth that is in Jesus.",
								"You were taught, with regard to your former way of life, to put off your old self, which is being corrupted by its deceitful desires;",
								"to be made new in the attitude of your minds;",
								"and to put on the new self, created to be like God in true righteousness and holiness.",
								"Therefore each of you must put off falsehood and speak truthfully to your neighbor, for we are all members of one body.",
								'"In your anger do not sin"[d]: Do not let the sun go down while you are still angry,',
								"and do not give the devil a foothold.",
								"Anyone who has been stealing must steal no longer, but must work, doing something useful with their own hands, that they may have something to share with those in need.",
								"Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs, that it may benefit those who listen.",
								"And do not grieve the Holy Spirit of God, with whom you were sealed for the day of redemption.",
								"Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice.",
								"Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
							],
						},
					],
					footnotes: {
						a: "Or _God_",
						b: "Psalm 68:18",
						c: "Or _the depths of the earth_",
						d: "Psalm 4:4 (see Septuagint)",
					},
				},
				{
					sections: [
						{
							title: "Instructions for Christian Living (Continued)",
							verses: [
								"Follow God's example, therefore, as dearly loved children",
								"and walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God.",
								"But among you there must not be even a hint of sexual immorality, or of any kind of impurity, or of greed, because these are improper for God's holy people.",
								"Nor should there be obscenity, foolish talk or coarse joking, which are out of place, but rather thanksgiving.",
								"For of this you can be sure: No immoral, impure or greedy person - such a person is an idolater - has any inheritance in the kingdom of Christ and of God.[a]",
								"Let no one deceive you with empty words, for because of such things God's wrath comes on those who are disobedient.",
								"Therefore do not be partners with them.",
								"For you were once darkness, but now you are light in the Lord. Live as children of light",
								"(for the fruit of the light consists in all goodness, righteousness and truth)",
								"and find out what pleases the Lord.",
								"Have nothing to do with the fruitless deeds of darkness, but rather expose them.",
								"It is shameful even to mention what the disobedient do in secret.",
								"But everything exposed by the light becomes visible - and everything that is illuminated becomes a light.",
								'This is why it is said: "Wake up, sleeper, rise from the dead, and Christ will shine on you."',
								"Be very careful, then, how you live - not as unwise but as wise,",
								"making the most of every opportunity, because the days are evil.",
								"Therefore do not be foolish, but understand what the Lord's will is.",
								"Do not get drunk on wine, which leads to debauchery. Instead, be filled with the Spirit,",
								"speaking to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord,",
								"always giving thanks to God the Father for everything, in the name of our Lord Jesus Christ.",
							],
						},
						{
							title: "Instructions for Christian Households",
							verses: [
								"Submit to one another out of reverence for Christ.",
								"Wives, submit yourselves to your own husbands as you do to the Lord.",
								"For the husband is the head of the wife as Christ is the head of the church, his body, of which he is the Savior.",
								"Now as the church submits to Christ, so also wives should submit to their husbands in everything.",
								"Husbands, love your wives, just as Christ loved the church and gave himself up for her",
								"to make her holy, cleansing[b] her by the washing with water through the word,",
								"and to present her to himself as a radiant church, without stain or wrinkle or any other blemish, but holy and blameless.",
								"In this same way, husbands ought to love their wives as their own bodies. He who loves his wife loves himself.",
								"After all, no one ever hated their own body, but they feed and care for their body, just as Christ does the church - ",
								"for we are members of his body.",
								'"For this reason a man will leave his father and mother and be united to his wife, and the two will become one flesh."[c]',
								"This is a profound mystery - but I am talking about Christ and the church.",
								"However, each one of you also must love his wife as he loves himself, and the wife must respect her husband.",
							],
						},
					],
					footnotes: {
						a: "Or _kingdom of the Messiah and God_",
						b: "Or _having cleansed_",
						c: "Gen. 2:24",
					},
				},
				{
					sections: [
						{
							title: "Instructions for Christian Households (Continued)",
							verses: [
								"Children, obey your parents in the Lord, for this is right.",
								'"Honor your father and mother" - which is the first commandment with a promise - ',
								'"so that it may go well with you and that you may enjoy long life on the earth."[a]',
								"Fathers,[b] do not exasperate your children; instead, bring them up in the training and instruction of the Lord.",
								"Slaves, obey your earthly masters with respect and fear, and with sincerity of heart, just as you would obey Christ.",
								"Obey them not only to win their favor when their eye is on you, but as slaves of Christ, doing the will of God from your heart.",
								"Serve wholeheartedly, as if you were serving the Lord, not people,",
								"because you know that the Lord will reward each one for whatever good they do, whether they are slave or free.",
								"And masters, treat your slaves in the same way. Do not threaten them, since you know that he who is both their Master and yours is in heaven, and there is no favoritism with him.",
							],
						},
						{
							title: "The Armor of God",
							verses: [
								"Finally, be strong in the Lord and in his mighty power.",
								"Put on the full armor of God, so that you can take your stand against the devil's schemes.",
								"For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.",
								"Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand.",
								"Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place,",
								"and with your feet fitted with the readiness that comes from the gospel of peace.",
								"In addition to all this, take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one.",
								"Take the helmet of salvation and the sword of the Spirit, which is the word of God.",
								"And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the Lord's people.",
								"Pray also for me, that whenever I speak, words may be given me so that I will fearlessly make known the mystery of the gospel,",
								"for which I am an ambassador in chains. Pray that I may declare it fearlessly, as I should.",
							],
						},
						{
							title: "Final Greetings",
							verses: [
								"Tychicus, the dear brother and faithful servant in the Lord, will tell you everything, so that you also may know how I am and what I am doing.",
								"I am sending him to you for this very purpose, that you may know how we are, and that he may encourage you.",
								"Peace to the brothers and sisters,[c] and love with faith from God the Father and the Lord Jesus Christ.",
								"Grace to all who love our Lord Jesus Christ with an undying love.[d]",
							],
						},
					],
					footnotes: {
						a: "Deut. 5:16",
						b: "Or _Parents_",
						c: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family.",
						d: "Or _Grace and immortality to all who love our Lord Jesus Christ._",
					},
				},
			],
		},
		{
			name: "Philippians",
			abbreviation: "P",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul and Timothy, servants of Christ Jesus, To all God's holy people in Christ Jesus at Philippi, together with the overseers and deacons[a]:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"I thank my God every time I remember you.",
								"In all my prayers for all of you, I always pray with joy",
								"because of your partnership in the gospel from the first day until now,",
								"being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.",
								"It is right for me to feel this way about all of you, since I have you in my heart and, whether I am in chains or defending and confirming the gospel, all of you share in God's grace with me.",
								"God can testify how I long for all of you with the affection of Christ Jesus.",
								"And this is my prayer: that your love may abound more and more in knowledge and depth of insight,",
								"so that you may be able to discern what is best and may be pure and blameless for the day of Christ,",
								"filled with the fruit of righteousness that comes through Jesus Christ - to the glory and praise of God.",
							],
						},
						{
							title: "Paul's Chains Advance the Gospel",
							verses: [
								"Now I want you to know, brothers and sisters,[b] that what has happened to me has actually served to advance the gospel.",
								"As a result, it has become clear throughout the whole palace guard[c] and to everyone else that I am in chains for Christ.",
								"And because of my chains, most of the brothers and sisters have become confident in the Lord and dare all the more to proclaim the gospel without fear.",
								"It is true that some preach Christ out of envy and rivalry, but others out of goodwill.",
								"The latter do so out of love, knowing that I am put here for the defense of the gospel.",
								"The former preach Christ out of selfish ambition, not sincerely, supposing that they can stir up trouble for me while I am in chains.",
								"But what does it matter? The important thing is that in every way, whether from false motives or true, Christ is preached. And because of this I rejoice. Yes, and I will continue to rejoice,",
								"for I know that through your prayers and God's provision of the Spirit of Jesus Christ what has happened to me will turn out for my deliverance.[d]",
								"I eagerly expect and hope that I will in no way be ashamed, but will have sufficient courage so that now as always Christ will be exalted in my body, whether by life or by death.",
								"For to me, to live is Christ and to die is gain.",
								"If I am to go on living in the body, this will mean fruitful labor for me. Yet what shall I choose? I do not know!",
								"I am torn between the two: I desire to depart and be with Christ, which is better by far;",
								"but it is more necessary for you that I remain in the body.",
								"Convinced of this, I know that I will remain, and I will continue with all of you for your progress and joy in the faith,",
								"so that through my being with you again your boasting in Christ Jesus will abound on account of me.",
							],
						},
						{
							title: "Life Worthy of the Gospel",
							verses: [
								"Whatever happens, conduct yourselves in a manner worthy of the gospel of Christ. Then, whether I come and see you or only hear about you in my absence, I will know that you stand firm in the one Spirit,[e] striving together as one for the faith of the gospel",
								"without being frightened in any way by those who oppose you. This is a sign to them that they will be destroyed, but that you will be saved - and that by God.",
								"For it has been granted to you on behalf of Christ not only to believe in him, but also to suffer for him,",
								"since you are going through the same struggle you saw I had, and now hear that I still have.",
							],
						},
					],
					footnotes: {
						a: "The word _deacons_ refers here to Christians designated to serve with the overseers/elders of the church in a variety of ways; similarly in Romans 16:1 and 1 Tim. 3:8,12.",
						b: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in verse 14; and in 3:1, 13, 17; 4:1, 8, 21.",
						c: "Or _whole palace_",
						d: "Or _vindication_; or _salvation_",
						e: "Or _in one spirit_",
					},
				},
				{
					sections: [
						{
							title: "Imitating Christ's Humility",
							verses: [
								"Therefore if you have any encouragement from being united with Christ, if any comfort from his love, if any common sharing in the Spirit, if any tenderness and compassion,",
								"then make my joy complete by being like-minded, having the same love, being one in spirit and of one mind.",
								"Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves,",
								"not looking to your own interests but each of you to the interests of the others.",
								"In your relationships with one another, have the same mindset as Christ Jesus:",
								"Who, being in very nature[a] God, did not consider equality with God something to be used to his own advantage;",
								"rather, he made himself nothing by taking the very nature[b] of a servant, being made in human likeness.",
								"And being found in appearance as a man, he humbled himself by becoming obedient to death - even death on a cross!",
								"Therefore God exalted him to the highest place and gave him the name that is above every name,",
								"that at the name of Jesus every knee should bow, in heaven and on earth and under the earth,",
								"and every tongue acknowledge that Jesus Christ is Lord, to the glory of God the Father.",
							],
						},
						{
							title: "Do Everything Without Grumbling",
							verses: [
								"Therefore, my dear friends, as you have always obeyed - not only in my presence, but now much more in my absence - continue to work out your salvation with fear and trembling,",
								"for it is God who works in you to will and to act in order to fulfill his good purpose.",
								"Do everything without grumbling or arguing,",
								'so that you may become blameless and pure, "children of God without fault in a warped and crooked generation."[c] Then you will shine among them like stars in the sky',
								"as you hold firmly to the word of life. And then I will be able to boast on the day of Christ that I did not run or labor in vain.",
								"But even if I am being poured out like a drink offering on the sacrifice and service coming from your faith, I am glad and rejoice with all of you.",
								"So you too should be glad and rejoice with me.",
							],
						},
						{
							title: "Timothy and Epaphroditus",
							verses: [
								"I hope in the Lord Jesus to send Timothy to you soon, that I also may be cheered when I receive news about you.",
								"I have no one else like him, who will show genuine concern for your welfare.",
								"For everyone looks out for their own interests, not those of Jesus Christ.",
								"But you know that Timothy has proved himself, because as a son with his father he has served with me in the work of the gospel.",
								"I hope, therefore, to send him as soon as I see how things go with me.",
								"And I am confident in the Lord that I myself will come soon.",
								"But I think it is necessary to send back to you Epaphroditus, my brother, co-worker and fellow soldier, who is also your messenger, whom you sent to take care of my needs.",
								"For he longs for all of you and is distressed because you heard he was ill.",
								"Indeed he was ill, and almost died. But God had mercy on him, and not on him only but also on me, to spare me sorrow upon sorrow.",
								"Therefore I am all the more eager to send him, so that when you see him again you may be glad and I may have less anxiety.",
								"So then, welcome him in the Lord with great joy, and honor people like him,",
								"because he almost died for the work of Christ. He risked his life to make up for the help you yourselves could not give me.",
							],
						},
					],
					footnotes: {
						a: "Or _in the form of_",
						b: "Or _the form_",
						c: "Deut. 32:5",
					},
				},
				{
					sections: [
						{
							title: "No Confidence in the Flesh",
							verses: [
								"Further, my brothers and sisters, rejoice in the Lord! It is no trouble for me to write the same things to you again, and it is a safeguard for you.",
								"Watch out for those dogs, those evildoers, those mutilators of the flesh.",
								"For it is we who are the circumcision, we who serve God by his Spirit, who boast in Christ Jesus, and who put no confidence in the flesh - ",
								"though I myself have reasons for such confidence. If someone else thinks they have reasons to put confidence in the flesh, I have more:",
								"circumcised on the eighth day, of the people of Israel, of the tribe of Benjamin, a Hebrew of Hebrews; in regard to the law, a Pharisee;",
								"as for zeal, persecuting the church; as for righteousness based on the law, faultless.",
								"But whatever were gains to me I now consider loss for the sake of Christ.",
								"What is more, I consider everything a loss because of the surpassing worth of knowing Christ Jesus my Lord, for whose sake I have lost all things. I consider them garbage, that I may gain Christ",
								"and be found in him, not having a righteousness of my own that comes from the law, but that which is through faith in[a] Christ - the righteousness that comes from God on the basis of faith.",
								"I want to know Christ - yes, to know the power of his resurrection and participation in his sufferings, becoming like him in his death,",
								"and so, somehow, attaining to the resurrection from the dead.",
								"Not that I have already obtained all this, or have already arrived at my goal, but I press on to take hold of that for which Christ Jesus took hold of me.",
								"Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead,",
								"I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.",
							],
						},
						{
							title: "Following Paul's Example",
							verses: [
								"All of us, then, who are mature should take such a view of things. And if on some point you think differently, that too God will make clear to you.",
								"Only let us live up to what we have already attained.",
								"Join together in following my example, brothers and sisters, and just as you have us as a model, keep your eyes on those who live as we do.",
								"For, as I have often told you before and now tell you again even with tears, many live as enemies of the cross of Christ.",
								"Their destiny is destruction, their god is their stomach, and their glory is in their shame. Their mind is set on earthly things.",
								"But our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ,",
								"who, by the power that enables him to bring everything under his control, will transform our lowly bodies so that they will be like his glorious body.",
							],
						},
					],
					footnotes: {
						a: "Or _through the faithfulness of_",
					},
				},
				{
					sections: [
						{
							title: "Closing Appeal for Steadfastness and Unity",
							verses: [
								"Therefore, my brothers and sisters, you whom I love and long for, my joy and crown, stand firm in the Lord in this way, dear friends!",
								"I plead with Euodia and I plead with Syntyche to be of the same mind in the Lord.",
								"Yes, and I ask you, my true companion, help these women since they have contended at my side in the cause of the gospel, along with Clement and the rest of my co-workers, whose names are in the book of life.",
							],
						},
						{
							title: "Final Exhortations",
							verses: [
								"Rejoice in the Lord always. I will say it again: Rejoice!",
								"Let your gentleness be evident to all. The Lord is near.",
								"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",
								"And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
								"Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable - if anything is excellent or praiseworthy - think about such things.",
								"Whatever you have learned or received or heard from me, or seen in me - put it into practice. And the God of peace will be with you.",
							],
						},
						{
							title: "Thanks for Their Gifts",
							verses: [
								"I rejoiced greatly in the Lord that at last you renewed your concern for me. Indeed, you were concerned, but you had no opportunity to show it.",
								"I am not saying this because I am in need, for I have learned to be content whatever the circumstances.",
								"I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want.",
								"I can do all this through him who gives me strength.",
								"Yet it was good of you to share in my troubles.",
								"Moreover, as you Philippians know, in the early days of your acquaintance with the gospel, when I set out from Macedonia, not one church shared with me in the matter of giving and receiving, except you only;",
								"for even when I was in Thessalonica, you sent me aid more than once when I was in need.",
								"Not that I desire your gifts; what I desire is that more be credited to your account.",
								"I have received full payment and have more than enough. I am amply supplied, now that I have received from Epaphroditus the gifts you sent. They are a fragrant offering, an acceptable sacrifice, pleasing to God.",
								"And my God will meet all your needs according to the riches of his glory in Christ Jesus.",
								"To our God and Father be glory for ever and ever. Amen.",
							],
						},
						{
							title: "Final Greetings",
							verses: [
								"Greet all God's people in Christ Jesus. The brothers and sisters who are with me send greetings.",
								"All God's people here send you greetings, especially those who belong to Caesar's household.",
								"The grace of the Lord Jesus Christ be with your spirit. Amen.[a]",
							],
						},
					],
					footnotes: {
						a: "Some manuscripts do not have _Amen_.",
					},
				},
			],
		},
		{
			name: "Colossians",
			abbreviation: "C",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
								"To God's holy people in Colossae, the faithful brothers and sisters[a] in Christ: Grace and peace to you from God our Father.[b]",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"We always thank God, the Father of our Lord Jesus Christ, when we pray for you,",
								"because we have heard of your faith in Christ Jesus and of the love you have for all God's people - ",
								"the faith and love that spring from the hope stored up for you in heaven and about which you have already heard in the true message of the gospel",
								"that has come to you. In the same way, the gospel is bearing fruit and growing throughout the whole world - just as it has been doing among you since the day you heard it and truly understood God's grace.",
								"You learned it from Epaphras, our dear fellow servant,[c] who is a faithful minister of Christ on our[d] behalf,",
								"and who also told us of your love in the Spirit.",
								"For this reason, since the day we heard about you, we have not stopped praying for you. We continually ask God to fill you with the knowledge of his will through all the wisdom and understanding that the Spirit gives,[e]",
								"so that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God,",
								"being strengthened with all power according to his glorious might so that you may have great endurance and patience,",
								"and giving joyful thanks to the Father, who has qualified you[f] to share in the inheritance of his holy people in the kingdom of light.",
								"For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves,",
								"in whom we have redemption, the forgiveness of sins.",
							],
						},
						{
							title: "The Supremacy of the Son of God",
							verses: [
								"The Son is the image of the invisible God, the firstborn over all creation.",
								"For in him all things were created: things in heaven and on earth, visible and invisible, whether thrones or powers or rulers or authorities; all things have been created through him and for him.",
								"He is before all things, and in him all things hold together.",
								"And he is the head of the body, the church; he is the beginning and the firstborn from among the dead, so that in everything he might have the supremacy.",
								"For God was pleased to have all his fullness dwell in him,",
								"and through him to reconcile to himself all things, whether things on earth or things in heaven, by making peace through his blood, shed on the cross.",
								"Once you were alienated from God and were enemies in your minds because of[g] your evil behavior.",
								"But now he has reconciled you by Christ's physical body through death to present you holy in his sight, without blemish and free from accusation - ",
								"if you continue in your faith, established and firm, and do not move from the hope held out in the gospel. This is the gospel that you heard and that has been proclaimed to every creature under heaven, and of which I, Paul, have become a servant.",
							],
						},
						{
							title: "Paul's Labor for the Church",
							verses: [
								"Now I rejoice in what I am suffering for you, and I fill up in my flesh what is still lacking in regard to Christ's afflictions, for the sake of his body, which is the church.",
								"I have become its servant by the commission God gave me to present to you the word of God in its fullness - ",
								"the mystery that has been kept hidden for ages and generations, but is now disclosed to the Lord's people.",
								"To them God has chosen to make known among the Gentiles the glorious riches of this mystery, which is Christ in you, the hope of glory.",
								"He is the one we proclaim, admonishing and teaching everyone with all wisdom, so that we may present everyone fully mature in Christ.",
								"To this end I strenuously contend with all the energy Christ so powerfully works in me.",
							],
						},
					],
					footnotes: {
						a: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in 4:15.",
						b: "Some manuscripts _Father and the Lord Jesus Christ_",
						c: "Or _slave_",
						d: "Some manuscripts _your_",
						e: "Or _all spiritual wisdom and understanding_",
						f: "Some manuscripts _us_",
						g: "Or _mind, as shown by_",
					},
				},
				{
					sections: [
						{
							title: "Paul's Labor for the Church (Continued)",
							verses: [
								"I want you to know how hard I am contending for you and for those at Laodicea, and for all who have not met me personally.",
								"My goal is that they may be encouraged in heart and united in love, so that they may have the full riches of complete understanding, in order that they may know the mystery of God, namely, Christ,",
								"in whom are hidden all the treasures of wisdom and knowledge.",
								"I tell you this so that no one may deceive you by fine-sounding arguments.",
								"For though I am absent from you in body, I am present with you in spirit and delight to see how disciplined you are and how firm your faith in Christ is.",
							],
						},
						{
							title: "Spiritual Fullness in Christ",
							verses: [
								"So then, just as you received Christ Jesus as Lord, continue to live your lives in him,",
								"rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.",
								"See to it that no one takes you captive through hollow and deceptive philosophy, which depends on human tradition and the elemental spiritual forces[a] of this world rather than on Christ.",
								"For in Christ all the fullness of the Deity lives in bodily form,",
								"and in Christ you have been brought to fullness. He is the head over every power and authority.",
								"In him you were also circumcised with a circumcision not performed by human hands. Your whole self ruled by the flesh[b] was put off when you were circumcised by[c] Christ,",
								"having been buried with him in baptism, in which you were also raised with him through your faith in the working of God, who raised him from the dead.",
								"When you were dead in your sins and in the uncircumcision of your flesh, God made you[d] alive with Christ. He forgave us all our sins,",
								"having canceled the charge of our legal indebtedness, which stood against us and condemned us; he has taken it away, nailing it to the cross.",
								"And having disarmed the powers and authorities, he made a public spectacle of them, triumphing over them by the cross.[e]",
							],
						},
						{
							title: "Freedom From Human Rules",
							verses: [
								"Therefore do not let anyone judge you by what you eat or drink, or with regard to a religious festival, a New Moon celebration or a Sabbath day.",
								"These are a shadow of the things that were to come; the reality, however, is found in Christ.",
								"Do not let anyone who delights in false humility and the worship of angels disqualify you. Such a person also goes into great detail about what they have seen; they are puffed up with idle notions by their unspiritual mind.",
								"They have lost connection with the head, from whom the whole body, supported and held together by its ligaments and sinews, grows as God causes it to grow.",
								"Since you died with Christ to the elemental spiritual forces of this world, why, as though you still belonged to the world, do you submit to its rules:",
								'"Do not handle! Do not taste! Do not touch!"?',
								"These rules, which have to do with things that are all destined to perish with use, are based on merely human commands and teachings.",
								"Such regulations indeed have an appearance of wisdom, with their self-imposed worship, their false humility and their harsh treatment of the body, but they lack any value in restraining sensual indulgence.",
							],
						},
					],
					footnotes: {
						a: "Or _the basic principles_; also in verse 20",
						b: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit; also in verse 13.",
						c: "Or _put off in the circumcision of_",
						d: "Some manuscripts _us_",
						e: "Or _them in him_",
					},
				},
				{
					sections: [
						{
							title: "Living as Those Made Alive in Christ",
							verses: [
								"Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God.",
								"Set your minds on things above, not on earthly things.",
								"For you died, and your life is now hidden with Christ in God.",
								"When Christ, who is your[a] life, appears, then you also will appear with him in glory.",
								"Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.",
								"Because of these, the wrath of God is coming.[b]",
								"You used to walk in these ways, in the life you once lived.",
								"But now you must also rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.",
								"Do not lie to each other, since you have taken off your old self with its practices",
								"and have put on the new self, which is being renewed in knowledge in the image of its Creator.",
								"Here there is no Gentile or Jew, circumcised or uncircumcised, barbarian, Scythian, slave or free, but Christ is all, and is in all.",
								"Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.",
								"Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.",
								"And over all these virtues put on love, which binds them all together in perfect unity.",
								"Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.",
								"Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit, singing to God with gratitude in your hearts.",
								"And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.",
							],
						},
						{
							title: "Instructions for Christian Households",
							verses: [
								"Wives, submit yourselves to your husbands, as is fitting in the Lord.",
								"Husbands, love your wives and do not be harsh with them.",
								"Children, obey your parents in everything, for this pleases the Lord.",
								"Fathers,[c] do not embitter your children, or they will become discouraged.",
								"Slaves, obey your earthly masters in everything; and do it, not only when their eye is on you and to curry their favor, but with sincerity of heart and reverence for the Lord.",
								"Whatever you do, work at it with all your heart, as working for the Lord, not for human masters,",
								"since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving.",
								"Anyone who does wrong will be repaid for their wrongs, and there is no favoritism.",
							],
						},
					],
					footnotes: {
						a: "Some manuscripts _our_",
						b: "Some early manuscripts _coming on those who are disobedient_",
						c: "Or _Parents_",
					},
				},
				{
					sections: [
						{
							title: "Instructions for Christian Households (Continued)",
							verses: ["Masters, provide your slaves with what is right and fair, because you know that you also have a Master in heaven."],
						},
						{
							title: "Further Instructions",
							verses: [
								"Devote yourselves to prayer, being watchful and thankful.",
								"And pray for us, too, that God may open a door for our message, so that we may proclaim the mystery of Christ, for which I am in chains.",
								"Pray that I may proclaim it clearly, as I should.",
								"Be wise in the way you act toward outsiders; make the most of every opportunity.",
								"Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone.",
							],
						},
						{
							title: "Final Greetings",
							verses: [
								"Tychicus will tell you all the news about me. He is a dear brother, a faithful minister and fellow servant[a] in the Lord.",
								"I am sending him to you for the express purpose that you may know about our[b] circumstances and that he may encourage your hearts.",
								"He is coming with Onesimus, our faithful and dear brother, who is one of you. They will tell you everything that is happening here.",
								"My fellow prisoner Aristarchus sends you his greetings, as does Mark, the cousin of Barnabas. (You have received instructions about him; if he comes to you, welcome him.)",
								"Jesus, who is called Justus, also sends greetings. These are the only Jews[c] among my co-workers for the kingdom of God, and they have proved a comfort to me.",
								"Epaphras, who is one of you and a servant of Christ Jesus, sends greetings. He is always wrestling in prayer for you, that you may stand firm in all the will of God, mature and fully assured.",
								"I vouch for him that he is working hard for you and for those at Laodicea and Hierapolis.",
								"Our dear friend Luke, the doctor, and Demas send greetings.",
								"Give my greetings to the brothers and sisters at Laodicea, and to Nympha and the church in her house.",
								"After this letter has been read to you, see that it is also read in the church of the Laodiceans and that you in turn read the letter from Laodicea.",
								'Tell Archippus: "See to it that you complete the ministry you have received in the Lord."',
								"I, Paul, write this greeting in my own hand. Remember my chains. Grace be with you.",
							],
						},
					],
					footnotes: {
						a: "Or _slave_; also in verse 12",
						b: "Some manuscripts _that he may know about your_",
						c: "Greek _only ones of the circumcision group_",
					},
				},
			],
		},
		{
			name: "Philemon",
			abbreviation: "Phm",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, a prisoner of Christ Jesus, and Timothy our brother, To Philemon our dear friend and fellow worker - ",
								"also to Apphia our sister and Archippus our fellow soldier - and to the church that meets in your home:",
								"Grace and peace to you[a] from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"I always thank my God as I remember you in my prayers,",
								"because I hear about your love for all his holy people and your faith in the Lord Jesus.",
								"I pray that your partnership with us in the faith may be effective in deepening your understanding of every good thing we share for the sake of Christ.",
								"Your love has given me great joy and encouragement, because you, brother, have refreshed the hearts of the Lord's people.",
							],
						},
						{
							title: "Paul's Plea for Onesimus",
							verses: [
								"Therefore, although in Christ I could be bold and order you to do what you ought to do,",
								"yet I prefer to appeal to you on the basis of love. It is as none other than Paul - an old man and now also a prisoner of Christ Jesus - ",
								"that I appeal to you for my son Onesimus,[b] who became my son while I was in chains.",
								"Formerly he was useless to you, but now he has become useful both to you and to me.",
								"I am sending him - who is my very heart - back to you.",
								"I would have liked to keep him with me so that he could take your place in helping me while I am in chains for the gospel.",
								"But I did not want to do anything without your consent, so that any favor you do would not seem forced but would be voluntary.",
								"Perhaps the reason he was separated from you for a little while was that you might have him back forever - ",
								"no longer as a slave, but better than a slave, as a dear brother. He is very dear to me but even dearer to you, both as a fellow man and as a brother in the Lord.",
								"So if you consider me a partner, welcome him as you would welcome me.",
								"If he has done you any wrong or owes you anything, charge it to me.",
								"I, Paul, am writing this with my own hand. I will pay it back - not to mention that you owe me your very self.",
								"I do wish, brother, that I may have some benefit from you in the Lord; refresh my heart in Christ.",
								"Confident of your obedience, I write to you, knowing that you will do even more than I ask.",
								"And one thing more: Prepare a guest room for me, because I hope to be restored to you in answer to your prayers.",
								"Epaphras, my fellow prisoner in Christ Jesus, sends you greetings.",
								"And so do Mark, Aristarchus, Demas and Luke, my fellow workers.",
								"The grace of the Lord Jesus Christ be with your spirit.",
							],
						},
					],
					footnotes: {
						a: "The Greek is plural; also in verses 22 and 25; elsewhere in this letter “you” is singular.",
						b: "_Onesimus_ means _useful_.",
					},
				},
			],
		},
	],
	concordance: null,
	biblicalReferences: [
		{
			reference: "G 3:6",
			source: "Genesis 15:6",
		},
		{
			reference: "G 3:8",
			source: "Genesis 12:3",
		},
		{
			reference: "G 3:8",
			source: "Genesis 18:18",
		},
		{
			reference: "G 3:8",
			source: "Genesis 22:18",
		},
		{
			reference: "G 3:10",
			source: "Deuteronomy 27:26",
		},
		{
			reference: "G 3:11",
			source: "Habakkuk 2:4",
		},
		{
			reference: "G 3:12",
			source: "Leviticus 18:5",
		},
		{
			reference: "G 3:13",
			source: "Deuteronomy 21:23",
		},
		{
			reference: "G 3:16",
			source: "Genesis 12:7",
		},
		{
			reference: "G 3:16",
			source: "Genesis 13:15",
		},
		{
			reference: "G 3:16",
			source: "Genesis 24:7",
		},
		{
			reference: "G 4:27",
			source: "Isaiah 54:1",
		},
		{
			reference: "G 4:30",
			source: "Genesis 21:10",
		},
		{
			reference: "G 5:14",
			source: "Leviticus 19:18",
		},
		{
			reference: "E 4:8",
			source: "Psalm 68:18",
		},
		{
			reference: "E 4:26",
			source: "Psalm 4:4",
		},
		{
			reference: "E 5:31",
			source: "Genesis 2:24",
		},
		{
			reference: "E 6:3",
			source: "Deuteronomy 5:16",
		},
		{
			reference: "P 2:15",
			source: "Deuteronomy 32:5",
		},
	],
	properNouns: [
		{
			noun: "Abba",
			type: "Proper Noun",
		},
		{
			noun: "Abraham",
			type: "Name",
		},
		{
			noun: "Abraham's",
			type: "Name",
		},
		{
			noun: "Antioch",
			type: "Place",
		},
		{
			noun: "Apphia",
			type: "Name",
		},
		{
			noun: "Arabia",
			type: "Place",
		},
		{
			noun: "Archippus",
			type: "Name",
		},
		{
			noun: "Aristarchus",
			type: "Name",
		},
		{
			noun: "Barnabas",
			type: "Name",
		},
		{
			noun: "Benjamin",
			type: "Name",
		},
		{
			noun: "Book",
			type: "Proper Noun",
		},
		{
			noun: "Caesar's",
			type: "Name",
		},
		{
			noun: "Cephas",
			type: "Name",
		},
		{
			noun: "Christ",
			type: "Name",
		},
		{
			noun: "Christ's",
			type: "Name",
		},
		{
			noun: "Cilicia",
			type: "Place",
		},
		{
			noun: "Clement",
			type: "Name",
		},
		{
			noun: "Colossae",
			type: "Place",
		},
		{
			noun: "Creator",
			type: "Name",
		},
		{
			noun: "Damascus",
			type: "Place",
		},
		{
			noun: "Deity",
			type: "Name",
		},
		{
			noun: "Demas",
			type: "Name",
		},
		{
			noun: "Epaphras",
			type: "Name",
		},
		{
			noun: "Epaphroditus",
			type: "Name",
		},
		{
			noun: "Ephesus",
			type: "Place",
		},
		{
			noun: "Euodia",
			type: "Name",
		},
		{
			noun: "Father",
			type: "Name",
		},
		{
			noun: "Galatia",
			type: "Place",
		},
		{
			noun: "Galatians",
			type: "Group",
		},
		{
			noun: "Gentile",
			type: "Name",
		},
		{
			noun: "Gentiles",
			type: "Group",
		},
		{
			noun: "God",
			type: "Name",
		},
		{
			noun: "God's",
			type: "Name",
		},
		{
			noun: "Greek",
			type: "Name",
		},
		{
			noun: "Hagar",
			type: "Name",
		},
		{
			noun: "Hebrew",
			type: "Name",
		},
		{
			noun: "Hebrews",
			type: "Group",
		},
		{
			noun: "Hierapolis",
			type: "Place",
		},
		{
			noun: "Holy",
			type: "Proper Noun",
		},
		{
			noun: "I",
			type: "Noun",
		},
		{
			noun: "Isaac",
			type: "Name",
		},
		{
			noun: "Israel",
			type: "Place",
		},
		{
			noun: "James",
			type: "Name",
		},
		{
			noun: "Jerusalem",
			type: "Place",
		},
		{
			noun: "Jesus",
			type: "Name",
		},
		{
			noun: "Jew",
			type: "Name",
		},
		{
			noun: "Jewish",
			type: "Name",
		},
		{
			noun: "Jews",
			type: "Group",
		},
		{
			noun: "John",
			type: "Name",
		},
		{
			noun: "Judaism",
			type: "Proper Noun",
		},
		{
			noun: "Judea",
			type: "Place",
		},
		{
			noun: "Justus",
			type: "Name",
		},
		{
			noun: "Laodicea",
			type: "Place",
		},
		{
			noun: "Laodiceans",
			type: "Group",
		},
		{
			noun: "Law",
			type: "Proper Noun",
		},
		{
			noun: "Lord",
			type: "Name",
		},
		{
			noun: "Lord's",
			type: "Name",
		},
		{
			noun: "Luke",
			type: "Name",
		},
		{
			noun: "Macedonia",
			type: "Place",
		},
		{
			noun: "Mark",
			type: "Name",
		},
		{
			noun: "Master",
			type: "Name",
		},
		{
			noun: "Mount Sinai",
			type: "Place",
		},
		{
			noun: "New Moon",
			type: "Proper Noun",
		},
		{
			noun: "Nympha",
			type: "Name",
		},
		{
			noun: "Onesimus",
			type: "Name",
		},
		{
			noun: "Paul",
			type: "Name",
		},
		{
			noun: "Peter",
			type: "Name",
		},
		{
			noun: "Pharisee",
			type: "Name",
		},
		{
			noun: "Philemon",
			type: "Name",
		},
		{
			noun: "Philippi",
			type: "Place",
		},
		{
			noun: "Philippians",
			type: "Group",
		},
		{
			noun: "Sabbath",
			type: "Proper Noun",
		},
		{
			noun: "Savior",
			type: "Name",
		},
		{
			noun: "Scripture",
			type: "Proper Noun",
		},
		{
			noun: "Scythian",
			type: "Name",
		},
		{
			noun: "Seed",
			type: "Proper Noun",
		},
		{
			noun: "Son",
			type: "Name",
		},
		{
			noun: "spirit",
			type: "Name",
		},
		{
			noun: "Syntyche",
			type: "Name",
		},
		{
			noun: "Syria",
			type: "Place",
		},
		{
			noun: "Thessalonica",
			type: "Place",
		},
		{
			noun: "Timothy",
			type: "Name",
		},
		{
			noun: "Titus",
			type: "Name",
		},
		{
			noun: "Tychicus",
			type: "Name",
		},
	],
	numbers: [
		{
			text: "430",
			number: 430,
		},
		{
			text: "all",
			number: 0.9,
		},
		{
			text: "eighth",
			number: 8,
		},
		{
			text: "fifteen",
			number: 15,
		},
		{
			text: "first",
			number: 1,
		},
		{
			text: "fourteen",
			number: 14,
		},
		{
			text: "many",
			number: 0.75,
		},
		{
			text: "none",
			number: 0,
		},
		{
			text: "nothing",
			number: 0,
		},
		{
			text: "once",
			number: 1,
		},
		{
			text: "one",
			number: 1,
		},
		{
			text: "some",
			number: 0.5,
		},
		{
			text: "three",
			number: 3,
		},
		{
			text: "two",
			number: 2,
		},
	],
	memoryVerses: {
		singles: [
			"G 1:10",
			"G 2:10",
			"G 2:20",
			"G 2:21",
			"G 3:11",
			"G 3:13",
			"G 3:14",
			"G 3:28",
			"G 3:29",
			"G 4:6",
			"G 4:7",
			"G 5:1",
			"G 5:6",
			"G 5:25",
			"G 6:1",
			"G 6:2",
			"G 6:7",
			"G 6:14",
			"E 1:3",
			"E 1:18",
			"E 2:10",
			"E 2:19",
			"E 2:22",
			"E 3:6",
			"E 3:12",
			"E 4:2",
			"E 4:3",
			"E 4:16",
			"E 4:29",
			"E 4:32",
			"E 5:21",
			"E 6:12",
			"E 6:13",
			"P 1:6",
			"P 1:21",
			"P 3:8",
			"P 3:12",
			"P 4:4",
			"P 4:8",
			"P 4:12",
			"P 4:13",
			"P 4:19",
			"C 1:15",
			"C 1:16",
			"C 2:8",
			"C 3:12",
			"C 3:15",
			"C 4:2",
			"Phm 1:6",
			"Phm 1:7",
		],
		multiples: [
			"G 1:3-5",
			"G 1:11-12",
			"G 2:15-16",
			"G 4:4-5",
			"G 5:13-14",
			"G 5:16-17",
			"G 5:22-23",
			"G 6:9-10",
			"E 1:4-6",
			"E 1:13-14",
			"E 1:22-23",
			"E 2:4-5",
			"E 2:8-9",
			"E 3:20-21",
			"E 4:4-6",
			"E 4:26-27",
			"E 5:1-2",
			"E 6:2-3",
			"E 6:7-8",
			"P 1:9-11",
			"P 2:3-4",
			"P 2:5-6",
			"P 2:9-11",
			"P 2:12-13",
			"P 3:10-11",
			"P 3:13-14",
			"P 4:6-7",
			"C 1:13-14",
			"C 1:18-19",
			"C 2:6-7",
			"C 2:13-14",
			"C 3:1-2",
			"C 3:13-14",
			"C 3:23-24",
			"C 4:5-6",
			"Phm 1:4-5",
			"Phm 1:15-16",
		],
	},
	prejumps: {
		singles: [
			"Am",
			"All",
			"I have",
			"I do",
			"Clearly",
			"Christ",
			"He",
			"There",
			"If",
			"Because",
			"So",
			"It",
			"For in Christ",
			"Since",
			"Brothers",
			"Carry",
			"Do not be",
			"May",
			"Praise",
			"I pray that the",
			"For we",
			"Consequently",
			"And in",
			"This",
			"In",
			"Be completely",
			"Make",
			"From",
			"Do not let",
			"Be kind",
			"Submit",
			"For our",
			"Therefore put",
			"being",
			"For to",
			"What",
			"Not",
			"Rejoice",
			"Finally,",
			"I know",
			"I can",
			"And my",
			"The",
			"For in him",
			"See",
			"Therefore, as",
			"Let",
			"Devote",
			"I pray that your",
			"Your",
		],
		multiples: [
			"Grace",
			"I want you",
			'"We',
			"But when",
			"You,",
			"So I",
			"But the",
			"Let",
			"For he chose",
			"And you",
			"And God",
			"But because",
			"For it",
			"Now",
			"There",
			'"In your anger',
			"Follow",
			'"Honor',
			"Serve",
			"And this",
			"Do nothing",
			"In your relationships",
			"Therefore God",
			"Therefore, my",
			"I want to",
			"Brothers",
			"Do not",
			"For he has",
			"And he",
			"So then,",
			"When",
			"Since,",
			"Bear",
			"Whatever",
			"Be",
			"I always",
			"Perhaps",
		],
	},
};

GEPCP.concordance = generateConcordance(GEPCP);
