var GEPCP_Decades = {
	books: {
		Galatians: {
			abbreviation: "G",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle - sent not from men nor by a man, but by Jesus Christ and God the Father, who raised him from the dead - ",
								"and all the brothers and sisters[a] with me, To the churches in Galatia:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ,",
								"who gave himself for our sins to rescue us from the present evil age, according to the will of our God and Father,",
								"to whom be glory for ever and ever. Amen.",
							],
						},
						{
							title: "No Other Gospel",
							verses: [
								"I am astonished that you are so quickly deserting the one who called you to live in the grace of Christ and are turning to a different gospel - ",
								"which is really no gospel at all. Evidently some people are throwing you into confusion and are trying to pervert the gospel of Christ.",
								"But even if we or an angel from heaven should preach a gospel other than the one we preached to you, let them be under God's curse!",
								"As we have already said, so now I say again: If anybody is preaching to you a gospel other than what you accepted, let them be under God's curse!",
								"Am I now trying to win the approval of human beings, or of God? Or am I trying to please people? If I were still trying to please people, I would not be a servant of Christ.",
							],
						},
						{
							title: "Paul Called by God",
							verses: [
								"I want you to know, brothers and sisters, that the gospel I preached is not of human origin.",
								"I did not receive it from any man, nor was I taught it; rather, I received it by revelation from Jesus Christ.",
								"For you have heard of my previous way of life in Judaism, how intensely I persecuted the church of God and tried to destroy it.",
								"I was advancing in Judaism beyond many of my own age among my people and was extremely zealous for the traditions of my fathers.",
								"But when God, who set me apart from my mother's womb and called me by his grace, was pleased",
								"to reveal his Son in me so that I might preach him among the Gentiles, my immediate response was not to consult any human being.",
								"I did not go up to Jerusalem to see those who were apostles before I was, but I went into Arabia. Later I returned to Damascus.",
								"Then after three years, I went up to Jerusalem to get acquainted with Cephas[b] and stayed with him fifteen days.",
								"I saw none of the other apostles - only James, the Lord's brother.",
								"I assure you before God that what I am writing you is no lie.",
								"Then I went to Syria and Cilicia.",
								"I was personally unknown to the churches of Judea that are in Christ.",
								'They only heard the report: "The man who formerly persecuted us is now preaching the faith he once tried to destroy."',
								"And they praised God because of me.",
							],
						},
					],
					footnotes: {
						a: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in verse 11; and in 3:15; 4:12, 28, 31; 5:11, 13; 6:1, 18.",
						b: "That is, Peter",
					},
				},
				{
					sections: [
						{
							title: "Paul Accepted by the Apostles",
							verses: [
								"Then after fourteen years, I went up again to Jerusalem, this time with Barnabas. I took Titus along also.",
								"I went in response to a revelation and, meeting privately with those esteemed as leaders, I presented to them the gospel that I preach among the Gentiles. I wanted to be sure I was not running and had not been running my race in vain.",
								"Yet not even Titus, who was with me, was compelled to be circumcised, even though he was a Greek.",
								"This matter arose because some false believers had infiltrated our ranks to spy on the freedom we have in Christ Jesus and to make us slaves.",
								"We did not give in to them for a moment, so that the truth of the gospel might be preserved for you.",
								"As for those who were held in high esteem - whatever they were makes no difference to me; God does not show favoritism - they added nothing to my message.",
								"On the contrary, they recognized that I had been entrusted with the task of preaching the gospel to the uncircumcised,[a] just as Peter had been to the circumcised.[b]",
								"For God, who was at work in Peter as an apostle to the circumcised, was also at work in me as an apostle to the Gentiles.",
								"James, Cephas[c] and John, those esteemed as pillars, gave me and Barnabas the right hand of fellowship when they recognized the grace given to me. They agreed that we should go to the Gentiles, and they to the circumcised.",
								"All they asked was that we should continue to remember the poor, the very thing I had been eager to do all along.",
							],
						},
						{
							title: "Paul Opposes Cephas",
							verses: [
								"When Cephas came to Antioch, I opposed him to his face, because he stood condemned.",
								"For before certain men came from James, he used to eat with the Gentiles. But when they arrived, he began to draw back and separate himself from the Gentiles because he was afraid of those who belonged to the circumcision group.",
								"The other Jews joined him in his hypocrisy, so that by their hypocrisy even Barnabas was led astray.",
								'When I saw that they were not acting in line with the truth of the gospel, I said to Cephas in front of them all, "You are a Jew, yet you live like a Gentile and not like a Jew. How is it, then, that you force Gentiles to follow Jewish customs?',
								'"We who are Jews by birth and not sinful Gentiles',
								"know that a person is not justified by the works of the law, but by faith in Jesus Christ. So we, too, have put our faith in Christ Jesus that we may be justified by faith in[d] Christ and not by the works of the law, because by the works of the law no one will be justified.",
								"\"But if, in seeking to be justified in Christ, we Jews find ourselves also among the sinners, doesn't that mean that Christ promotes sin? Absolutely not!",
								"If I rebuild what I destroyed, then I really would be a lawbreaker.",
								'"For through the law I died to the law so that I might live for God.',
								"I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.",
								'I do not set aside the grace of God, for if righteousness could be gained through the law, Christ died for nothing!"[e]',
							],
						},
					],
					footnotes: {
						a: "That is, Gentiles",
						b: "That is, Jews; also in verses 8 and 9",
						c: "That is, Peter; also in verses 11 and 14",
						d: "Or _but through the faithfulness of … justified on the basis of the faithfulness of_",
						e: "Some interpreters end the quotation after verse 14.",
					},
				},
				{
					sections: [
						{
							title: "Faith or Works of the Law",
							verses: [
								"You foolish Galatians! Who has bewitched you? Before your very eyes Jesus Christ was clearly portrayed as crucified.",
								"I would like to learn just one thing from you: Did you receive the Spirit by the works of the law, or by believing what you heard?",
								"Are you so foolish? After beginning by means of the Spirit, are you now trying to finish by means of the flesh?[a]",
								"Have you experienced[b] so much in vain - if it really was in vain?",
								"So again I ask, does God give you his Spirit and work miracles among you by the works of the law, or by your believing what you heard?",
								'So also Abraham "believed God, and it was credited to him as righteousness."[c]',
								"Understand, then, that those who have faith are children of Abraham.",
								'Scripture foresaw that God would justify the Gentiles by faith, and announced the gospel in advance to Abraham: "All nations will be blessed through you."[d]',
								"So those who rely on faith are blessed along with Abraham, the man of faith.",
								'For all who rely on the works of the law are under a curse, as it is written: "Cursed is everyone who does not continue to do everything written in the Book of the Law."[e]',
								'Clearly no one who relies on the law is justified before God, because "the righteous will live by faith."[f]',
								'The law is not based on faith; on the contrary, it says, "The person who does these things will live by them."[g]',
								'Christ redeemed us from the curse of the law by becoming a curse for us, for it is written: "Cursed is everyone who is hung on a pole."[h]',
								"He redeemed us in order that the blessing given to Abraham might come to the Gentiles through Christ Jesus, so that by faith we might receive the promise of the Spirit.",
							],
						},
						{
							title: "The Law and the Promise",
							verses: [
								"Brothers and sisters, let me take an example from everyday life. Just as no one can set aside or add to a human covenant that has been duly established, so it is in this case.",
								'The promises were spoken to Abraham and to his seed. Scripture does not say "and to seeds," meaning many people, but "and to your seed,"[i] meaning one person, who is Christ.',
								"What I mean is this: The law, introduced 430 years later, does not set aside the covenant previously established by God and thus do away with the promise.",
								"For if the inheritance depends on the law, then it no longer depends on the promise; but God in his grace gave it to Abraham through a promise.",
								"Why, then, was the law given at all? It was added because of transgressions until the Seed to whom the promise referred had come. The law was given through angels and entrusted to a mediator.",
								"A mediator, however, implies more than one party; but God is one.",
								"Is the law, therefore, opposed to the promises of God? Absolutely not! For if a law had been given that could impart life, then righteousness would certainly have come by the law.",
								"But Scripture has locked up everything under the control of sin, so that what was promised, being given through faith in Jesus Christ, might be given to those who believe.",
							],
						},
						{
							title: "Children of God",
							verses: [
								"Before the coming of this faith,[j] we were held in custody under the law, locked up until the faith that was to come would be revealed.",
								"So the law was our guardian until Christ came that we might be justified by faith.",
								"Now that this faith has come, we are no longer under a guardian.",
								"So in Christ Jesus you are all children of God through faith,",
								"for all of you who were baptized into Christ have clothed yourselves with Christ.",
								"There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus.",
								"If you belong to Christ, then you are Abraham's seed, and heirs according to the promise.",
							],
						},
					],
					footnotes: {
						a: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit.",
						b: "Or _suffered_",
						c: "Gen. 15:6",
						d: "Gen. 12:3; 18:18; 22:18",
						e: "Deut. 27:26",
						f: "Hab. 2:4",
						g: "Lev. 18:5",
						h: "Deut. 21:23",
						i: "Gen. 12:7; 13:15; 24:7",
						j: "Or _through the faithfulness of Jesus … {23}Before faith came_",
					},
				},
				{
					sections: [
						{
							title: "Children of God (Continued)",
							verses: [
								"What I am saying is that as long as an heir is underage, he is no different from a slave, although he owns the whole estate.",
								"The heir is subject to guardians and trustees until the time set by his father.",
								"So also, when we were underage, we were in slavery under the elemental spiritual forces[a] of the world.",
								"But when the set time had fully come, God sent his Son, born of a woman, born under the law,",
								"to redeem those under the law, that we might receive adoption to sonship.[b]",
								'Because you are his sons, God sent the Spirit of his Son into our hearts, the Spirit who calls out, "Abba,[c] Father."',
								"So you are no longer a slave, but God's child; and since you are his child, God has made you also an heir.",
							],
						},
						{
							title: "Paul's Concern for the Galatians",
							verses: [
								"Formerly, when you did not know God, you were slaves to those who by nature are not gods.",
								"But now that you know God - or rather are known by God - how is it that you are turning back to those weak and miserable forces[d]? Do you wish to be enslaved by them all over again?",
								"You are observing special days and months and seasons and years!",
								"I fear for you, that somehow I have wasted my efforts on you.",
								"I plead with you, brothers and sisters, become like me, for I became like you. You did me no wrong.",
								"As you know, it was because of an illness that I first preached the gospel to you,",
								"and even though my illness was a trial to you, you did not treat me with contempt or scorn. Instead, you welcomed me as if I were an angel of God, as if I were Christ Jesus himself.",
								"Where, then, is your blessing of me now? I can testify that, if you could have done so, you would have torn out your eyes and given them to me.",
								"Have I now become your enemy by telling you the truth?",
								"Those people are zealous to win you over, but for no good. What they want is to alienate you from us, so that you may have zeal for them.",
								"It is fine to be zealous, provided the purpose is good, and to be so always, not just when I am with you.",
								"My dear children, for whom I am again in the pains of childbirth until Christ is formed in you,",
								"how I wish I could be with you now and change my tone, because I am perplexed about you!",
							],
						},
						{
							title: "Hagar and Sarah",
							verses: [
								"Tell me, you who want to be under the law, are you not aware of what the law says?",
								"For it is written that Abraham had two sons, one by the slave woman and the other by the free woman.",
								"His son by the slave woman was born according to the flesh, but his son by the free woman was born as the result of a divine promise.",
								"These things are being taken figuratively: The women represent two covenants. One covenant is from Mount Sinai and bears children who are to be slaves: This is Hagar.",
								"Now Hagar stands for Mount Sinai in Arabia and corresponds to the present city of Jerusalem, because she is in slavery with her children.",
								"But the Jerusalem that is above is free, and she is our mother.",
								'For it is written: "Be glad, barren woman, you who never bore a child; shout for joy and cry aloud, you who were never in labor; because more are the children of the desolate woman than of her who has a husband."[e]',
								"Now you, brothers and sisters, like Isaac, are children of promise.",
								"At that time the son born according to the flesh persecuted the son born by the power of the Spirit. It is the same now.",
								"But what does Scripture say? \"Get rid of the slave woman and her son, for the slave woman's son will never share in the inheritance with the free woman's son.\"[f]",
								"Therefore, brothers and sisters, we are not children of the slave woman, but of the free woman.",
							],
						},
					],
					footnotes: {
						a: "Or _under the basic principles_",
						b: "The Greek word for _adoption to sonship_ is a legal term referring to the full legal standing of an adopted male heir in Roman culture.",
						c: "Aramaic for _Father_",
						d: "Or _principles_",
						e: "Isaiah 54:1",
						f: "Gen. 21:10",
					},
				},
				{
					sections: [
						{
							title: "Freedom in Christ",
							verses: [
								"It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.",
								"Mark my words! I, Paul, tell you that if you let yourselves be circumcised, Christ will be of no value to you at all.",
								"Again I declare to every man who lets himself be circumcised that he is obligated to obey the whole law.",
								"You who are trying to be justified by the law have been alienated from Christ; you have fallen away from grace.",
								"For through the Spirit we eagerly await by faith the righteousness for which we hope.",
								"For in Christ Jesus neither circumcision nor uncircumcision has any value. The only thing that counts is faith expressing itself through love.",
								"You were running a good race. Who cut in on you to keep you from obeying the truth?",
								"That kind of persuasion does not come from the one who calls you.",
								'"A little yeast works through the whole batch of dough."',
								"I am confident in the Lord that you will take no other view. The one who is throwing you into confusion, whoever that may be, will have to pay the penalty.",
								"Brothers and sisters, if I am still preaching circumcision, why am I still being persecuted? In that case the offense of the cross has been abolished.",
								"As for those agitators, I wish they would go the whole way and emasculate themselves!",
							],
						},
						{
							title: "Life by the Spirit",
							verses: [
								"You, my brothers and sisters, were called to be free. But do not use your freedom to indulge the flesh[a]; rather, serve one another humbly in love.",
								'For the entire law is fulfilled in keeping this one command: "Love your neighbor as yourself."[b]',
								"If you bite and devour each other, watch out or you will be destroyed by each other.",
								"So I say, walk by the Spirit, and you will not gratify the desires of the flesh.",
								"For the flesh desires what is contrary to the Spirit, and the Spirit what is contrary to the flesh. They are in conflict with each other, so that you are not to do whatever[c] you want.",
								"But if you are led by the Spirit, you are not under the law.",
								"The acts of the flesh are obvious: sexual immorality, impurity and debauchery;",
								"idolatry and witchcraft; hatred, discord, jealousy, fits of rage, selfish ambition, dissensions, factions",
								"and envy; drunkenness, orgies, and the like. I warn you, as I did before, that those who live like this will not inherit the kingdom of God.",
								"But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness,",
								"gentleness and self-control. Against such things there is no law.",
								"Those who belong to Christ Jesus have crucified the flesh with its passions and desires.",
								"Since we live by the Spirit, let us keep in step with the Spirit.",
								"Let us not become conceited, provoking and envying each other.",
							],
						},
					],
					footnotes: {
						a: "In contexts like this, the Greek word for _flesh_ (_sarx_) refers to the sinful state of human beings, often presented as a power in opposition to the Spirit; also in verses 16, 17, 19 and 24; and in 6:8.",
						b: "Lev. 19:18",
						c: "Or _you do not do what_",
					},
				},
				{
					sections: [
						{
							title: "Doing Good to All",
							verses: [
								"Brothers and sisters, if someone is caught in a sin, you who live by the Spirit should restore that person gently. But watch yourselves, or you also may be tempted.",
								"Carry each other's burdens, and in this way you will fulfill the law of Christ.",
								"If anyone thinks they are something when they are not, they deceive themselves.",
								"Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else,",
								"for each one should carry their own load.",
								"Nevertheless, the one who receives instruction in the word should share all good things with their instructor.",
								"Do not be deceived: God cannot be mocked. A man reaps what he sows.",
								"Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life.",
								"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
								"Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.",
							],
						},
						{
							title: "Not Circumcision but the New Creation",
							verses: [
								"See what large letters I use as I write to you with my own hand!",
								"Those who want to impress people by means of the flesh are trying to compel you to be circumcised. The only reason they do this is to avoid being persecuted for the cross of Christ.",
								"Not even those who are circumcised keep the law, yet they want you to be circumcised that they may boast about your circumcision in the flesh.",
								"May I never boast except in the cross of our Lord Jesus Christ, through which[a] the world has been crucified to me, and I to the world.",
								"Neither circumcision nor uncircumcision means anything; what counts is the new creation.",
								"Peace and mercy to all who follow this rule - to[b] the Israel of God.",
								"From now on, let no one cause me trouble, for I bear on my body the marks of Jesus.",
								"The grace of our Lord Jesus Christ be with your spirit, brothers and sisters. Amen.",
							],
						},
					],
					footnotes: {
						a: "Or _whom_",
						b: "Or _rule and to_",
					},
				},
			],
		},
		Ephesians: {
			abbreviation: "E",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle of Christ Jesus by the will of God, To God's holy people in Ephesus,[a] the faithful in Christ Jesus:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Praise for Spiritual Blessings in Christ",
							verses: [
								"Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.",
								"For he chose us in him before the creation of the world to be holy and blameless in his sight. In love",
								"he[b] predestined us for adoption to sonship[c] through Jesus Christ, in accordance with his pleasure and will - ",
								"to the praise of his glorious grace, which he has freely given us in the One he loves.",
								"In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace",
								"that he lavished on us. With all wisdom and understanding,",
								"he[d] made known to us the mystery of his will according to his good pleasure, which he purposed in Christ,",
								"to be put into effect when the times reach their fulfillment - to bring unity to all things in heaven and on earth under Christ.",
								"In him we were also chosen,[e] having been predestined according to the plan of him who works out everything in conformity with the purpose of his will,",
								"in order that we, who were the first to put our hope in Christ, might be for the praise of his glory.",
								"And you also were included in Christ when you heard the message of truth, the gospel of your salvation. When you believed, you were marked in him with a seal, the promised Holy Spirit,",
								"who is a deposit guaranteeing our inheritance until the redemption of those who are God's possession - to the praise of his glory.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"For this reason, ever since I heard about your faith in the Lord Jesus and your love for all God's people,",
								"I have not stopped giving thanks for you, remembering you in my prayers.",
								"I keep asking that the God of our Lord Jesus Christ, the glorious Father, may give you the Spirit[f] of wisdom and revelation, so that you may know him better.",
								"I pray that the eyes of your heart may be enlightened in order that you may know the hope to which he has called you, the riches of his glorious inheritance in his holy people,",
								"and his incomparably great power for us who believe. That power is the same as the mighty strength",
								"he exerted when he raised Christ from the dead and seated him at his right hand in the heavenly realms,",
								"far above all rule and authority, power and dominion, and every name that is invoked, not only in the present age but also in the one to come.",
								"And God placed all things under his feet and appointed him to be head over everything for the church,",
								"which is his body, the fullness of him who fills everything in every way.",
							],
						},
					],
					footnotes: {
						a: "Some early manuscripts do not have _in Ephesus._",
						b: "Or _sight in love. {5} He_",
						c: "The Greek word for _adoption to sonship_ is a legal term referring to the full legal standing of an adopted male heir in Roman culture.",
						d: "Or _us with all wisdom and understanding. {9} And he_",
						e: "Or _were made heirs_",
						f: "Or _a spirit_",
					},
				},
			],
		},
		Philippians: {
			abbreviation: "P",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul and Timothy, servants of Christ Jesus, To all God's holy people in Christ Jesus at Philippi, together with the overseers and deacons[a]:",
								"Grace and peace to you from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"I thank my God every time I remember you.",
								"In all my prayers for all of you, I always pray with joy",
								"because of your partnership in the gospel from the first day until now,",
								"being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.",
								"It is right for me to feel this way about all of you, since I have you in my heart and, whether I am in chains or defending and confirming the gospel, all of you share in God's grace with me.",
								"God can testify how I long for all of you with the affection of Christ Jesus.",
								"And this is my prayer: that your love may abound more and more in knowledge and depth of insight,",
								"so that you may be able to discern what is best and may be pure and blameless for the day of Christ,",
								"filled with the fruit of righteousness that comes through Jesus Christ - to the glory and praise of God.",
							],
						},
						{
							title: "Paul's Chains Advance the Gospel",
							verses: [
								"Now I want you to know, brothers and sisters,[b] that what has happened to me has actually served to advance the gospel.",
								"As a result, it has become clear throughout the whole palace guard[c] and to everyone else that I am in chains for Christ.",
								"And because of my chains, most of the brothers and sisters have become confident in the Lord and dare all the more to proclaim the gospel without fear.",
								"It is true that some preach Christ out of envy and rivalry, but others out of goodwill.",
								"The latter do so out of love, knowing that I am put here for the defense of the gospel.",
								"The former preach Christ out of selfish ambition, not sincerely, supposing that they can stir up trouble for me while I am in chains.",
								"But what does it matter? The important thing is that in every way, whether from false motives or true, Christ is preached. And because of this I rejoice. Yes, and I will continue to rejoice,",
								"for I know that through your prayers and God's provision of the Spirit of Jesus Christ what has happened to me will turn out for my deliverance.[d]",
								"I eagerly expect and hope that I will in no way be ashamed, but will have sufficient courage so that now as always Christ will be exalted in my body, whether by life or by death.",
								"For to me, to live is Christ and to die is gain.",
								"If I am to go on living in the body, this will mean fruitful labor for me. Yet what shall I choose? I do not know!",
								"I am torn between the two: I desire to depart and be with Christ, which is better by far;",
								"but it is more necessary for you that I remain in the body.",
								"Convinced of this, I know that I will remain, and I will continue with all of you for your progress and joy in the faith,",
								"so that through my being with you again your boasting in Christ Jesus will abound on account of me.",
							],
						},
						{
							title: "Life Worthy of the Gospel",
							verses: [
								"Whatever happens, conduct yourselves in a manner worthy of the gospel of Christ. Then, whether I come and see you or only hear about you in my absence, I will know that you stand firm in the one Spirit,[e] striving together as one for the faith of the gospel",
								"without being frightened in any way by those who oppose you. This is a sign to them that they will be destroyed, but that you will be saved - and that by God.",
								"For it has been granted to you on behalf of Christ not only to believe in him, but also to suffer for him,",
								"since you are going through the same struggle you saw I had, and now hear that I still have.",
							],
						},
					],
					footnotes: {
						a: "The word _deacons_ refers here to Christians designated to serve with the overseers/elders of the church in a variety of ways; similarly in Romans 16:1 and 1 Tim. 3:8,12.",
						b: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in verse 14; and in 3:1, 13, 17; 4:1, 8, 21.",
						c: "Or _whole palace_",
						d: "Or _vindication_; or _salvation_",
						e: "Or _in one spirit_",
					},
				},
			],
		},
		Colossians: {
			abbreviation: "C",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
								"To God's holy people in Colossae, the faithful brothers and sisters[a] in Christ: Grace and peace to you from God our Father.[b]",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"We always thank God, the Father of our Lord Jesus Christ, when we pray for you,",
								"because we have heard of your faith in Christ Jesus and of the love you have for all God's people - ",
								"the faith and love that spring from the hope stored up for you in heaven and about which you have already heard in the true message of the gospel",
								"that has come to you. In the same way, the gospel is bearing fruit and growing throughout the whole world - just as it has been doing among you since the day you heard it and truly understood God's grace.",
								"You learned it from Epaphras, our dear fellow servant,[c] who is a faithful minister of Christ on our[d] behalf,",
								"and who also told us of your love in the Spirit.",
								"For this reason, since the day we heard about you, we have not stopped praying for you. We continually ask God to fill you with the knowledge of his will through all the wisdom and understanding that the Spirit gives,[e]",
								"so that you may live a life worthy of the Lord and please him in every way: bearing fruit in every good work, growing in the knowledge of God,",
								"being strengthened with all power according to his glorious might so that you may have great endurance and patience,",
								"and giving joyful thanks to the Father, who has qualified you[f] to share in the inheritance of his holy people in the kingdom of light.",
								"For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves,",
								"in whom we have redemption, the forgiveness of sins.",
							],
						},
						{
							title: "The Supremacy of the Son of God",
							verses: [
								"The Son is the image of the invisible God, the firstborn over all creation.",
								"For in him all things were created: things in heaven and on earth, visible and invisible, whether thrones or powers or rulers or authorities; all things have been created through him and for him.",
								"He is before all things, and in him all things hold together.",
								"And he is the head of the body, the church; he is the beginning and the firstborn from among the dead, so that in everything he might have the supremacy.",
								"For God was pleased to have all his fullness dwell in him,",
								"and through him to reconcile to himself all things, whether things on earth or things in heaven, by making peace through his blood, shed on the cross.",
								"Once you were alienated from God and were enemies in your minds because of[g] your evil behavior.",
								"But now he has reconciled you by Christ's physical body through death to present you holy in his sight, without blemish and free from accusation - ",
								"if you continue in your faith, established and firm, and do not move from the hope held out in the gospel. This is the gospel that you heard and that has been proclaimed to every creature under heaven, and of which I, Paul, have become a servant.",
							],
						},
						{
							title: "Paul's Labor for the Church",
							verses: [
								"Now I rejoice in what I am suffering for you, and I fill up in my flesh what is still lacking in regard to Christ's afflictions, for the sake of his body, which is the church.",
								"I have become its servant by the commission God gave me to present to you the word of God in its fullness - ",
								"the mystery that has been kept hidden for ages and generations, but is now disclosed to the Lord's people.",
								"To them God has chosen to make known among the Gentiles the glorious riches of this mystery, which is Christ in you, the hope of glory.",
								"He is the one we proclaim, admonishing and teaching everyone with all wisdom, so that we may present everyone fully mature in Christ.",
								"To this end I strenuously contend with all the energy Christ so powerfully works in me.",
							],
						},
					],
					footnotes: {
						a: "The Greek word for _brothers and sisters_ (_adelphoi_) refers here to believers, both men and women, as part of God’s family; also in 4:15.",
						b: "Some manuscripts _Father and the Lord Jesus Christ_",
						c: "Or _slave_",
						d: "Some manuscripts _your_",
						e: "Or _all spiritual wisdom and understanding_",
						f: "Some manuscripts _us_",
						g: "Or _mind, as shown by_",
					},
				},
			],
		},
		Philemon: {
			abbreviation: "Phm",
			chapters: [
				{
					sections: [
						{
							title: "Untitled Section",
							verses: [
								"Paul, a prisoner of Christ Jesus, and Timothy our brother, To Philemon our dear friend and fellow worker - ",
								"also to Apphia our sister and Archippus our fellow soldier - and to the church that meets in your home:",
								"Grace and peace to you[a] from God our Father and the Lord Jesus Christ.",
							],
						},
						{
							title: "Thanksgiving and Prayer",
							verses: [
								"I always thank my God as I remember you in my prayers,",
								"because I hear about your love for all his holy people and your faith in the Lord Jesus.",
								"I pray that your partnership with us in the faith may be effective in deepening your understanding of every good thing we share for the sake of Christ.",
								"Your love has given me great joy and encouragement, because you, brother, have refreshed the hearts of the Lord's people.",
							],
						},
						{
							title: "Paul's Plea for Onesimus",
							verses: [
								"Therefore, although in Christ I could be bold and order you to do what you ought to do,",
								"yet I prefer to appeal to you on the basis of love. It is as none other than Paul - an old man and now also a prisoner of Christ Jesus - ",
								"that I appeal to you for my son Onesimus,[b] who became my son while I was in chains.",
								"Formerly he was useless to you, but now he has become useful both to you and to me.",
								"I am sending him - who is my very heart - back to you.",
								"I would have liked to keep him with me so that he could take your place in helping me while I am in chains for the gospel.",
								"But I did not want to do anything without your consent, so that any favor you do would not seem forced but would be voluntary.",
								"Perhaps the reason he was separated from you for a little while was that you might have him back forever - ",
								"no longer as a slave, but better than a slave, as a dear brother. He is very dear to me but even dearer to you, both as a fellow man and as a brother in the Lord.",
								"So if you consider me a partner, welcome him as you would welcome me.",
								"If he has done you any wrong or owes you anything, charge it to me.",
								"I, Paul, am writing this with my own hand. I will pay it back - not to mention that you owe me your very self.",
								"I do wish, brother, that I may have some benefit from you in the Lord; refresh my heart in Christ.",
								"Confident of your obedience, I write to you, knowing that you will do even more than I ask.",
								"And one thing more: Prepare a guest room for me, because I hope to be restored to you in answer to your prayers.",
								"Epaphras, my fellow prisoner in Christ Jesus, sends you greetings.",
								"And so do Mark, Aristarchus, Demas and Luke, my fellow workers.",
								"The grace of the Lord Jesus Christ be with your spirit.",
							],
						},
					],
					footnotes: {
						a: "The Greek is plural; also in verses 22 and 25; elsewhere in this letter “you” is singular.",
						b: "_Onesimus_ means _useful_.",
					},
				},
			],
		},
	},
	concordance: undefined,
	memoryVerses: {
		singles: [
			"G 1:10",
			"G 2:10",
			"G 2:20",
			"G 2:21",
			"G 3:11",
			"G 3:13",
			"G 3:14",
			"G 3:28",
			"G 3:29",
			"G 4:6",
			"G 4:7",
			"G 5:1",
			"G 5:6",
			"G 5:25",
			"G 6:1",
			"G 6:2",
			"G 6:7",
			"G 6:14",
			"E 1:3",
			"E 1:18",
			"P 1:6",
			"P 1:21",
			"C 1:15",
			"C 1:16",
			"Phm 1:6",
			"Phm 1:7",
		],
		multiples: [
			"G 1:3-5",
			"G 1:11-12",
			"G 2:15-16",
			"G 4:4-5",
			"G 5:13-14",
			"G 5:16-17",
			"G 5:22-23",
			"G 6:9-10",
			"E 1:4-6",
			"E 1:13-14",
			"E 1:22-23",
			"P 1:9-11",
			"C 1:13-14",
			"C 1:18-19",
			"Phm 1:4-5",
			"Phm 1:15-16",
		],
	},
	prejumps: {
		singles: [
			"Am",
			"All",
			"I have",
			"I do",
			"Clearly",
			"Christ",
			"He",
			"There",
			"If",
			"Because",
			"So",
			"It",
			"For in Christ",
			"Since",
			"Brothers",
			"Carry",
			"Do",
			"May",
			"Praise",
			"I pray that the",
			"being",
			"For to",
			"The",
			"For in him",
			"I pray that your",
			"Your",
		],
		multiples: ["Grace", "I want", '"We', "But when", "You,", "So", "But the", "Let", "For he chose", "And you", "And God", "And this", "For he has", "And he", "I always", "Perhaps"],
	},
};

GEPCP_Decades.concordance = generateConcordance(GEPCP_Decades);
